= SDP Pipeline Libraries

This repository contains https://boozallen.com[Booz Allen's] pipeline libraries that integrate with the https://plugins.jenkins.io/templating-engine/[Jenkins Templating Engine].

If you want to learn more, the best place to get started is the https://boozallen.github.io/sdp-docs/sdp-libraries/[documentation]. 

=== Usage
In order to use the different libraries in this repository, you can configure this repository as a library source, for a detailed example of how to do this you may refer to this lab: https://boozallen.github.io/sdp-docs/learning-labs/1/jte-the-basics/3-first-libraries.html#_configure_the_library_source it is recommended that rather than using this repository directly, you fork this repository and use the fork instead. This helps to ensure that you have greater control in version management. 

Also ensure that in addition to whichever library you wish to use you include the "sdp" library. This helps to resolve a number of dependency errors you may otherwise face.

== Repository Structure

=== Libraries

The libraries themselves can be found under the `libraries` directory.  Each subdirectory corresponds to the name of the library, and the basename of the groovy files held within are the `steps` contributed by that library. 

=== Unit Tests

The SDP Pipeline Libraries leverage https://github.com/ExpediaGroup/jenkins-spock[Jenkins Spock] as a unit testing framework for testing the library steps.  

Each library that has unit tests has a subdirectory under `test` containing the individual Specification files for the library. 

To execute the unit tests, run `make test`. 

=== Documentation 

https://antora.org[Antora] is used as the documentation framework.  For each library you'll find an AsciiDoc file under `docs/modules/ROOT/pages` that outlines the steps contributed by the library, how to configure the library in your pipeline configuration file, what types of artifacts are generated, and any external dependencies the library may have.  

To build the documentation run `make docs`.  You can then open `docs/html/index.html` to view the generated documentation.
