= SonarQube

SonarQube is a tool used for *static code analysis*. Static code analysis is validating code as-written against industry standard practices.  It will help you find best practice violations and potential security vulnerabilities.

Organizations can define Quality Profiles which are custom rule profiles that projects must use.  Quality Gates are then rules defining the organizational policies for code quality. SDP will, by default, fail the build if the Quality Gate fails.

SonarQube has a specific scanner for .NET applications. See https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-msbuild/[SonarScanner for .NET] for more details.

==  Steps Contributed

.Steps
|===
| Step | Description

| ``dotnet_static_code_analysis()``
| Leverages the dotnet sonar-scanner cli to perform static code analysis and sends results to the configured SonarQube server

|===

== Library Configuration Options

.SonarQube Library Configuration Options
|===
| Field | Description | Default Value

| `installation_name`
| The name of the SonarQube installation configured in `Manage Jenkins > Configure System`
| "SonarQube"

| `credential_id`
| The Jenkins credential ID to use when authenticating to SonarQube.  Can either be a valid username/password or an API Token stored in a Secret Text credential type. 
| If unset, the library will check if the installation defined via `installation_name` has a server authorization token configured.  If a server authorization token has been provided in the plugin configuration, then that will be the default.  If unset, then a credential id of "sonarqube" will be assumed.

| `wait_for_quality_gate`
| Whether or not to wait for SonarQube to send a webhook back to Jenkins notifying with the Quality Gate result
| true 

| `enforce_quality_gate`
| Determine whether the build will fail if the code does not pass the quality gate
| true

| `stage_display_name`
| Purely aesthetic.  The name of the stage block during analysis for pipeline visualization in the Jenkins console.
| "SonarQube Analysis"

| `timeout_duration`
| The number representing how long to wait for the Quality Gate response before timing out
| 1

| `timeout_unit`
| One of [ "NANOSECONDS", "MICROSECONDS", "MILLISECONDS", "SECONDS", "MINUTES", "HOURS", "DAYS" ]
| "HOURS" 

| `cli_parameters`
| a list of additional CLI analysis parameters to pass the `sonar-scanner` cli.
| [ ]

| `unstash`
| a list of pre-existing stashes to try to unstash. Useful if a previous step creates compiled classes or test results for SonarQube to inspect. 
| [ "TestResults" ] 


| `project_key`
| Project key for the sonarqube project.
| ${env.ORG_NAME}:${env.REPO_NAME}


| `test_output_dir`
| The directory to store results from tests and code coverage. SonarQube will look at this directory for metrics. 
| "TestResults" 


| `coverage_settings_file`
| The settings file to define code coverage.
| "coverage.settings" 

|===

=== Environment Variables

It's possible to use pipeline environment variables to populate the analysis parameters.  This is especially useful when used with one of the source code management libraries to reference the branch name. 

==== Configuration File 

The .NET Sonar Scanner does not use a configuration file. However, we do require a `coverlet.settings` file for code coverage scanning.

coverlet.settings
[source, xml]
----

<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat Code Coverage">
        <Configuration>
          <Format>opencover</Format>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
----

==== CLI Parameters 

See https://docs.sonarqube.org/latest/analysis/analysis-parameters/[SonarQube Documentation] for list of CLI parameters.

.pipeline_config.groovy
[source,groovy]
----
libraries{
    sonarqube{
        cli_parameters = [ 
            "/d:sonar.dotnet.excludeTestProjects=true"
        ]
    }
}
----

==  External Dependencies

* A SonarQube server should be deployed
* The https://plugins.jenkins.io/sonar/[SonarQube Scanner] plugin should be installed
* The SonarQube Installation must be configured in `Manage Jenkins > Configure System > SonarQube servers`
** The "Enable injection of SonarQube server configuration as build environment variables" checkbox should be checked

== Authentication

This library supports both username/password and API Token authentication to SonarQube. 

If anonymous access is disabled for the SonarQube Server (*it probably should be*), then you will need to create an API Token and store it as a Secret Text credential in the Jenkins Credential Store for reference in `Manage Jenkins > Configure System > Sonarqube servers` as the `Server authentication token`.

==  Troubleshooting

==  FAQ

=== What is the difference between this and the sonarqube scanner?

Applications built with .NET are now required to use the .NET Sonar Scanner. This scanner does *not* use the configuration file and must pass in the project key and other CLI arguments directly.

=== How do I set the project key?

If the `project_key` configuration variable is not set, this step will use the repository name as the project key.
Set the `project_key` configuration variable to change the project key.
