= Terraform

This library leverages https://www.terraform.io/intro/index.html[Terraform] to manage deployments of Infrastructure as Code to different environments. 

== Steps Contributed

.Steps
|===
| *Step* | *Description* 

| ``deploy_to(application_environment)``
| performs a terraform apply 

|===

== Library Configuration Options

=== Working Directory 

The working directory from which to run Terraform commands can be specified on the application environment pass to ``deploy_to`` or within the library configuration. 

.Pipeline Configuration 
[source, groovy]
----
application_environments{
  dev
  prod{
    terraform{
      working_directory = "terraform-prod" 
    }
  }
}

libraries{
  terraform{
    working_directory = "default-directory"
  }
}
----

.Pipeline Template
[source, groovy]
----
/*
  because dev.terraform.working_directory is not set
  the library will fallback to the library's configuration
  and execute terraform commands within the "default" directory
*/
deploy_to dev 
/*
  because prod.terraform.working_directory is set to "terraform-prod"
  the terraform commands will be executed within ./terraform-prod 
*/
deploy_to prod 
----

[NOTE]
====
If the working directory is not defined on either the library configuration or the application environment then the default value `"."` will be used. 
====

=== Secrets 

This library allows you to configure secrets as environment variables.  This can be done in both the library configuration or application environments.  There are two types of secrets currently supported:  secret text and username/password credentials. These credentials must be stored are in the Jenkins credential store. 

.Library Secrets Syntax
[source, groovy]
----
libraries{
  terraform{
    secrets{
      someTextCredential{
        type = "text"
        name = "VARIABLE_NAME"
        id = "some-credential-id"
      }
      someUsernamePasswordCredential{
        type = "usernamePassword"
        usernameVar = "USER"
        passwordVar = "PASS"
        id = "some-credential-id"
      }
    }
  }
}
----

The name of each credential block is not important, and only used when describing configuration errors found by the step. 

To pass secrets on a per application environment basis, define a `app_env.terraform.secrets` block: 

.Application Environments Secrets Syntax
[source, groovy]
----
application_environments{
  prod{
    terraform{
      secrets{
        someTextCredential{
          type = "text"
          name = "VARIABLE_NAME"
          id = "some-credential-id"
        }
        someUsernamePasswordCredential{
          type = "usernamePassword"
          usernameVar = "USER"
          passwordVar = "PASS"
          id = "some-credential-id"
        }
      }
    }
  }
}
----

[IMPORTANT]
====
If the same secret block is defined on both the application environment and the library configuration, the application environment secret definition will be used.
====

== Providers 

The https://github.com/boozallen/sdp-images/tree/master/terraform[SDP Terraform Pipeline Image] can bundle custom providers, if necessary. 

=== Sysdig Provider

The https://github.com/draios/terraform-provider-sysdig[Sysdig Terraform Provider] is bundled with the terraform image. To configure this provider, it is advisable to create secrets for `SYSDIG_SECURE_API_TOKEN` and `SYSDIG_MONITOR_API_TOKEN`.  These environment variables can be consumed by the provider to configure the required secrets. 
== Additional Common Configuration Options for SDP library steps
.Common Configuration Options
|===
| *Field* | *Description* | *Default Value*

| agentType
| This sets the agentType of the jenkins agent on which this step should be run. This value overrides the settings in the SDP library. Possible values are "kubernetes" "docker" and "generic".
| value from default SDP library configuration else "generic"

| nodeLabel
| This provides the label of the static jenkins agent on which to execute this pipeline step. This value is applicable for agentType "docker" and "generic". For "kubernetes" agent type, the nodes are dynamically launched and the label is automaticaly generated.
| value from default SDP library configuration else none

| images
| This block is used when agentType is "docker". It provies information on accessing the Docker image this step  needs to use. The values in this block overrrides the values in the SDP library configuration. Nonetheless, using the combination of what is declared here and the default SDP library configuration values, this library step must be able to access and pull the image it needs from the registry
|

| images.registry
| This sets the registry the where this step expects to find its Docker images
| value from default SDP library configuration else none

| images.repository
| The first https://forums.docker.com/t/docker-registry-v2-spec-and-repository-naming-rule/5466[path component] in the repository name, e.g. if your images follow the format ``my-registry.com/sdp/*``, this would be *sdp*
| value from default SDP library configuration else none

| images.cred
| Credentials used to pull images from the specified repository
| value from default SDP library configuration else none

| images.img
| Name of the default image to use
| "terraform"

| images.docker_args
| Arguments to use when starting the container. Uses the same flags as `docker run`
| value from default SDP library configuration else none

| podSpec
| This block is used when agentType is "kubernetes". It provies information on accessing the container images that needs to be used to launch a dynamic pod in which this step is to be executed. The values in this block overrrides  the values in the SDP library configuration. Nonetheless, using the combination of what is declared here and in the SDP library configuration values, the step must be able to access and pull the image it needs from the registry. In addition to information on the container image, this block also provides the namespace in which to launch the pod and the cloud / cluster into which the pod must be launched
|

| podSpec.registry
| This sets the registry the library step expects to find the container images
| value from default SDP library configuration else none

| podSpec.repository
| The first https://forums.docker.com/t/docker-registry-v2-spec-and-repository-naming-rule/5466[path component] in the repository name, e.g. if your images follow the format ``my-registry.com/sdp/*``, this would be *sdp*
| value from default SDP library configuration else none

| podSpec.cred
| Credentials used to pull images from the specified repository
| value from default SDP library configuration else none

| podSpec.img
| Name of the image to use
| "terraform"

| podSpec.cloud
| Name of the kubernetes cluster / cloud as defined in the Jenkins master configuration to launch the pod in
| value from default SDP library configuration else  "kubernetes"

| podSpec.namespace
| Name of the kubernetes namespace to launch the pod in (this namespace must exist in the cluster)
| value from default SDP library configuration else default

|===

[IMPORTANT]
====

The value in "images.registry" _does_ include the protocol (http/https) while the value in "podSpec.registry" does not include the protocol (http/https).

====

== Example Configuration Snippet - Common Configuration Options

[source,groovy]
----
libraries{
  agentType = "kubernetes"
  podSpec{
    cloud = "prod-cluster"
    namespace = "sdp"
    registry = "docker-registry.default.svc:5000"
    repository = "sdp"
    cred = "docker-registry-secret"
    img = "terraform"
  }
}

or

libraries{
  agentType = "docker"
  nodeLabel = "sdp-agent"
  images{
    registry = "https://docker-registry.default.svc:5000"
    repository = "sdp"
    cred = "docker-registry-secret"
    docker_args = ""
    img = "terraform"
  }
}

or

libraries{
  agentType = "generic"
  nodeLabel = "sdp-agent"
}

----
== External Dependencies 

== Troubleshooting
