= Configuring Jenkins Agent Types

The configuration options provided for the SDP pipeline steps allow to select on which type Jenkins agent nodes  different pieces of the piepline are run. The three possible agent types are differentiated by the how the pipeline code is implemented inside each of these agent types. It accomodates for Jenkins agents of three types

-  Dynamically launched "kubernetes" agents. Here the pipeline code is executed inside a container that is provisioned inside a  pod that is launched dynamically to execute only the specified code.

- Static "docker" agents that support Docker in Docker functionality. Here the pipeline code is executed inside a docker container that is deployed inside of the agent (docker in docker) which in itself could be a stand alone docker container or a docker container inside of a kubernetes pod. 

-  Static "generic" agents that can be of any type (Kubernetes pods, Virtual Machines, Docker containers - anything that can act as a Jenkins Agent). Here the code is simply executed in the agent's workspace.

==  Important notes to remember when configuring agents for pipeline steps
====
Configuration for agents is allowed in the "sdp" library configuration (usually default values and values common to all sdp pipeline steps) as well as in the pipeline step specific configuration (to override default values or customize a value)
 
The order of evaluation is always as follows

Order of evaluation of “img” field - “pipeline library step configuration” then “default image name implictly associated ** with the step for steps that require custom images” then “default "sdp" library configuration”

**For implicit default of container names for each step where it exists, please see individual pipeline step "podspec.img" or "images.img" configuration field

Order of evaluation of all other fields - “pipeline library step configuration” then “default "sdp" library configuration”

After evaluation, the combination of registry, repo, img and cred values should yield a valid path to fetch the image from for "kubernetes" and "docker" agent types. 
====

== Kubernetes Agents

These are dynamically launched ephermal Kubernetes pods that act as Jenkins Agents and specifically execute the associated body of actions inside a specified container and then die. The configuration of such agents is accomplished by setting the following fields 

.Kubernetes Agent Configuration Options
|===
| *Field* | *Description*  | *Default Value*

| agentType
| This is set to "kubernetes" for deploying dynamically launched kuberenetes agents
| value from library step's configuration else value from default SDP library configuration else "generic"

| podSpec
| This block is used when agentType is "kubernetes". It provies information on accessing the container images that needs to be used to launch a dynamic pod in which a step is to be executed. Using the combination of what is declared in the pipeline steps  and in the "sdp" library configuration , it must be possible to access and pull the image needed from the registry. Optionally, in addition to information on the container image, this block also provides the namespace in which to launch the pod and the cloud / cluster into which the pod must be launched
|

| podSpec.registry
| This sets the registry the library step expects to find the container images
| value from library step's configuration else value from default SDP library configuration else none

| podSpec.repository
| The first https://forums.docker.com/t/docker-registry-v2-spec-and-repository-naming-rule/5466[path component] in the repository name, e.g. if your images follow the format ``my-registry.com/sdp/*``, this would be *sdp*
| value from library step's configuration else value from default SDP library configuration else none

| podSpec.cred
| Credentials used to pull images from the specified repository
| value from library step's configuration else value from default SDP library configuration else none

| podSpec.img
| Name of the image to use
| value from library step's configuration else implicit default for library step else value from default SDP library configuration else ERROR

| podSpec.cloud
| Name of the kubernetes cluster / cloud as defined in the Jenkins master configuration to launch the pod in
| value from library step's configuration else value from default SDP library configuration else  "kubernetes"

| podSpec.namespace
| Name of the kubernetes namespace to launch the pod in (this namespace must exist in the cluster)
| value from library step's configuration else value from default SDP library configuration else default

|===

== Example  - A simple setup for agent type "kubernetes"

For static code analysis a  dynamic pod is launched in the default namespace with container image docker-registry.default.svc:5000/sdp/sonar-scanner. Gitlab and other pipeline steps are executed on a dynamic pod launched in the default namespace wih container image docker-registry.default.svc:5000/sdp/default-centos.

[source,groovy]
----

libraries{
  sdp{
    agentType = “kubernetes”
    podSpec{
        registry = “docker-registry.default.svc:5000”
        repository = “sdp”
        img = “default-centos”
} 
sonar-scanner {}
gitlab{}

----

== Example  - A more complex setup for agent type "kubernetes"

A dynamic pod is launched in the “test-cluster” in the “test-sdp” namespace with container image test-registry.test-sdp.svc:5000/sdp/sonar-scanner-new-version pulled with credentials “test-registry-cred” to execute static code analysis. The gitlab and other pipeline steps are executed on a dynamic pod launched in the mgmt-cluster in the sdp namespace with container image custom-registry.sdp.svc:5000/sdp/default-centos pulled with credentials “custom-registry-cred”.

[source,groovy]
----

libraries{
  sdp{
     agentType = “kubernetes”
     podSpec{
        cloud = “mgmt-cluster”
        namespace = “sdp”
        registry = “custom-registry.sdp.svc:5000”
        repository = “sdp”
        img = “default-centos”
        cred = “custom-registry-cred”
     }
  }
  sonar-scanner {
    podSpec{
        cloud = “test-cluster”
        namespace = “test-sdp”
        registry = “test-registry.sdp.svc:5000”
        repository = “test-sdp”
        img = “sonar-scanner-new-version”
        cred = “test-registry-cred”
     }

  }
  gitlab{}
}

----

== Docker Agents

These are so named because they execute pipeline steps inside a specific docker container running inside a Jenkins Agent docker container. These are static docker-in-docker (DinD) Jenkins Agents. Note that these Agents could be staic Kubernetes pods or Docker ontainers. In either case they should be capable of Docker inside Docker functionality. These agents can be assigned “node labels” and pipeline steps and stages could be assigned to run on a node with a particular node label. The configuration of such agents is accomplished by setting the following fields


.Docker Agent Configuration Options
|===
| *Field* | *Description*  | *Default Value*

| agentType
| This is set to "docker" for deploying docker agents
| value from library step's configuration else value from default SDP library configuration else "generic"

| nodeLabel
| This provides the label of the static jenkins agent on which to execute this pipeline step. 
| value from library step's configuration else value from default SDP library configuration else none

| images
| This block is used when agentType is "docker". Using the combination of what is declared pipeline step and in the default SDP library configuration values, it must be possible to access and pull the image needed from the registry
| 

| images.registry
| This sets the registry where this step expects to find its Docker images
| value from library step's configuration else value from default SDP library configuration else none

| images.repository
| The first https://forums.docker.com/t/docker-registry-v2-spec-and-repository-naming-rule/5466[path component] in the repository name, e.g. if your images follow the format ``my-registry.com/sdp/*``, this would be *sdp*
| value from library step's configuration else value from default SDP library configuration else none

| images.cred
| Credentials used to pull images from the specified repository
| value from library step's configuration else value from default SDP library configuration else none

| images.img
| Name of the default image to use
| value from library step's configuration else implicit default for library step else value from default SDP library configuration else ERROR

| images.docker_args
| Arguments to use when starting the container. Uses the same flags as `docker run`
| value from library step's configuration else value from default SDP library configuration else none

|===

== Example - a simple setup for agent type "docker"

Static code analysis is perfomed on any available Jenkins agent inside the container image docker-registry.default.svc:5000/sdp/sonar-scanner. The gitlab and other pipeline steps are executed on any available Jenkins-Agent inside the container image docker-registry.default.svc:5000/sdp/default-centos

[source,groovy]
----

libraries{
  sdp{
    agentType = “docker”
    images{
        registry = “docker-registry.default.svc:5000”
        repository = “sdp”
        img = “default-centos”
} 
sonar-scanner {}
gitlab{}

----

== Example - a more complex setup for agent type "docker"

Static code analysis is performed on any available node labelled “sdp-test-agents” inside container image test-registry.sdp.svc:5000/test-sdp/sonar-scanner-new-version pulled with credentials “test-registry-cred”. The gitlab and other pipeline steps are executed on any available agent with label “default-agents” inside container image custom-registry.sdp.svc:5000/sdp/default-centos pulled with credentials “custom-registry-cred”.

[source,groovy]
----
libraries{
  sdp{
     agentType = “docker”
     nodeLabel = “default-agents”
     images{
        registry = “custom-registry.sdp.svc:5000”
        repository = “sdp”
        img = “default-centos”
        cred = “custom-registry-cred”
     }
  }
  sonar-scanner {
       nodeLabel = “sdp-test-agents”
       images{
         img = “sonar-scanner-new-version
         registry = “test-registry.sdp.svc:5000”
         repository = “test-sdp”
         cred = “test-registry-cred”
       }
  }
  gitlab{}
}

----


== Generic Agents
These are static Jenkins Agents which could be Kubernetes pods, Virtual Machines, Docker containers or really any type of machine which acts like a Jenkins Agent and on which Jenkins pipelines steps can be executed.  These agents can be assigned “node labels” and pipeline steps and stages could be assigned to run on a node with a particular node label. The configuration of such agents is accomplished by setting the following fields


.Generic Agent Configuration Options
|===
| *Field* | *Description*  | *Default Value*

| agentType
| This is set to "generic" for generic  agents (this is the default agent type)
| value from library step's configuration else value from default SDP library configuration else "generic"

| nodeLabel
| This provides the label of the static jenkins agent on which to execute this pipeline step. 
| value from library step's configuration else value from default SDP library configuration else none


|===

== Example - a setup for agent type "generic"

Static code analysis is performed on any available node labeled "sdp-agents". The gitlab and other pipeline steps are executed on any available agent with node label “default-agents”.

[source,groovy]
----

libraries{
  sdp{
     agentType = “generic”
     nodeLabel = “default-agents”
  }
  sonar-scanner {
       nodeLabel = “sdp-agents”
  }
  gitlab{}
}


----

== Example - a more complex multi-cluster multi agent-type setup 

Static code analysis will be run on a dynamically launched pod in cluster named “kubernetes” with container image registry-one.default.svc:5000/sdp/sonar-scanner with credentials registry-one-cred. Owasp-zap will run on any available Jenkins node inside container registry-two.default.svc:5000/sdp/zap pulled with credentials registry-two-cred. Owasp-dependency-check will run inside a dynamically launched pod in cluster named “new-cluster” in the default namespace with container image registry-one.default.svc:5000/sdp/zap pulled with credentials registry-one-cred. Gitlab and other generic steps will run on any available Jenkins agent.

[source,groovy]
----

libraries{
  sdp{
     podSpec{
        registry = “registry-one.default.svc:5000”
        repository = “sdp”
        cred = “registry-one-cred”
        img = “default-centos”
     }
     images{
        registry = “registry-two.default.svc:5000”
        repository = “sdp”
        img = “default-centos”
        cred = “registry-two-cred”
     }
  }
  sonarqube {
       agentType = “kubernetes”
  }
  owasp_zap{
      agentType = “docker”
   }
  owasp_dep_check{
     agentType = “kubernetes”
     podSpec{
        cloud = “new-cluster”
     }
   }   
  gitlab{}
}


----

[IMPORTANT]
====

The value in "images.registry" _does_ include the protocol (http/https) while the value in "podSpec.registry" does not include the protocol (http/https).

====
