= Create A New Library

This page will outline the steps for adding a new SDP library that's ready for others to consume and contribute to. 

== Ask yourself some questions

. Does the library already exist? :) 
. Could this functionality be added to an existing library? 
. Is this library going to be usable by anyone else who wants to use this tool? 

If the library doesn't already exist, wouldn't make more sense as an addition to an existing library, and represents a use case that will be applicable outside of your current situation then it's likely a good candidate for contribution! 

== Fork the SDP Libraries repository

This project follows a standard https://gist.github.com/Chaser324/ce0505fbed06b947d962[Fork Contribution Model], so if you haven't, go ahead and fork the https://github.com/boozallen/sdp-libraries[SDP Pipeline Libraries Repository]. 

== Determine a name for the library

* A library's name is determined by the name of the directory that's going to contain the implemented steps.  
* The name should be all lowercase, snake_case, and the same as the tool or process being integrated. 
* Of course, ensure this tool has 

[source, bash]
----
# from the root of the repository
mkdir libraries/<name_of_new_library>
----

== Implement the library's steps 

Go on over to JTE's xref:jte:library-development:getting_started.adoc[Library Development] documentation to learn how to create libraries. 

There are a few conventions the SDP Pipeline Libraries have adopted, outlined below:

=== Check SDP library's helper methods

The xref:libraries/sdp.adoc[SDP library] exists to implement common functionality required by the other libraries.  It's worthwhile to see if any of those steps are going to be useful to you during library development.

=== Add an SDP Pipeline Image (if necessary)

The SDP Pipeline Libraries try to install as few plugins on the Jenkins instance and as few tools on the underlying infrastructure as possible.  We run portions of the pipeline inside container images, leveraging them as runtime pipeline environments. The existing container images used for this purpose can be found in the https://github.com/boozallen/sdp-images[SDP Pipeline Images] repository.  

If your library requires runtime dependencies, like a CLI, capture them in a container image and open a PR to the SDP Pipeline Images repository.

In your step implementations, the image that is to be used should be overridable but default to the image hosted via GitHub Package Registry on the SDP Pipeline Images repository. 

[NOTE]
====
If your library requires runtime dependencies, your new library will not be accepted until the required image has been merged and published to the SDP Pipeline Images repository. 
====

== Add documentation for the library 

=== Create the documentation page

Libraries are required to have a documentation page to be accepted. 

To keep the library documentation consistent, copy the templated documentation page as a starting point to fill in: 

[source, asciidoc]
....
include::example$library_doc_template.adoc[]
....

[NOTE]
====
You can either: 

. copy and paste the above code snippet into docs/modules/ROOT/pages/libraries/<library_name>.adoc 
. run ``cp docs/modules/ROOT/examples/library_doc_template.adoc docs/modules/ROOT/pages/libraries/<library_name>.adoc``
====

=== Add the library to nav.adoc 

https://antora.org[Antora] is used to build the documentation.  Antora leverages ``nav.adoc`` files to specify the page tree.  Add the new library under the ``.Libraries`` header in docs/modules/ROOT/nav.adoc alphabetically.  

=== Update the landing page libraries table

The landing page for the SDP Pipeline Libraries has a table that outlines each library and a high-level description of the library.  Update this table in docs/modules/ROOT/pages/index.adoc.

=== Preview your documentation

You can run ``make docs`` at the root of the repository to build the documentation as static HTML.  You can either open ``docs/html/index.html`` or run an nginx container locally to view the docs:

[source, bash]
----
make docs
docker run --name docs -v $(pwd)/docs/html:/usr/share/nginx/html -e "NGINX_HOST=localhost" -p 80:80 -d nginx
# docs now viewable on http://localhost
----

== Add unit tests 

It's highly encouraged that unit tests be written for the library.  

. Create a subdirectory under `test` named after the library: `test/<library_name>`
. Read the xref:unit_testing/index.adoc[Unit Testing Documentation]
. Write some tests for your steps

== Add a library configuration file 

To help prevent configuration errors, you can also xref:jte:library-development:validate_library_parameters.adoc[validate the library parameters]. 

== Open a Pull Request

The library is now done!  At this point you should have: 

. A new library with steps implemented using the SDP library's helpers if necessary
. A new SDP Pipeline Image corresponding to the new library for its runtime dependencies 
. Documentation for the library 
. Unit tests for the library 
. A strategy for validating the library's configuration parameters

These will all be confirmed during PR review. 
