= Test Execution

For our SDP Pipeline Libraries, tests are placed in a directory called `unit-tests` within the library directory.

== Executing tests with Gradle

This repo has been set up to run Jenkins-Spock tests using Gradle. 

Currently, Gradle 6.3.0 running on JDK 8 is required. These can be downloaded on OSX via:

```
# gradle via sdkman: https://sdkman.io/
curl -s "https://get.sdkman.io" | bash
source "/Users/joshuaearnest/.sdkman/bin/sdkman-init.sh"
sdk install gradle 6.3

# java8
brew install adoptopenjdk8
export JAVA_8_HOME=$(/usr/libexec/java_home -v1.8)
alias java8='export JAVA_HOME=$JAVA_8_HOME'
java8
```

To run all tests, from the root of the sdp-libraries repository, run `just test`.

You can also run a tests for a specific library with `just test "*.<library name>*"`. Or, you can run all tests in a specific file with `just test "*.<filename>"`.

== Executing tests with Docker

The unit tests can also be executed via Docker, though it is much slower. From the root of the sdp-libraries repository, run `docker run -v ${PWD}:/app -w/app gradle:6.3.0-jdk8 gradle --no-daemon test --tests '*'`.

Replace `'*'` with `'*.<library name>*'` or `'*.<filename>'` as desired.

== Viewing Test Results

Spock will create an HTML test report.  After running tests, you can run `open target/reports/tests/test/index.html`.