site:
  title: Solutions Delivery Platform
  url: http://localhost
  start_page: sdp-libraries::index.adoc
content:
  sources:
  - url: ./..
    branches: HEAD
    start_path: docs
  - url: https://github.com/jenkinsci/templating-engine-plugin
    branches: main 
    start_path: docs 
ui: 
  bundle: 
    url: https://github.com/boozallen/sdp-docs-skin/releases/download/1.1/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
