name: CI
on:
  pull_request:
    branches: 
      - main
jobs:
  MarkdownLint:
    runs-on: ubuntu-latest
    if: github.repository == 'boozallen/sdp-libraries'
    container:
      image: davidanson/markdownlint-cli2:0.4.0
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: markdownlint-cli2
        run: markdownlint-cli2
  Vale:
    runs-on: ubuntu-latest
    if: github.repository == 'boozallen/sdp-libraries'
    container:
      image: jdkato/vale:v2.18.0
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: vale
        run: vale docs libraries
  Unit_Test:
    runs-on: ubuntu-latest
    if: github.repository == 'boozallen/sdp-libraries'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: --no-daemon test
    - uses: actions/upload-artifact@v1
      with:
        name: test-results
        path: target/reports
